---
title: "Integrative Research Project"
author: "Team 57"
date: "21-6-2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(plyr)
library(dplyr)
library(ggplot2)
library(reshape2)
```

```{r}
dataframe <- read.csv("IRPdata.csv")[-c(2, 71),18:71]
df <- dataframe[dataframe$Q1 == "I Consent",]
df <- df[df$Q1.5 == "Yes, I do",]
df <- df[df$Q3 != "Other",]
df <- cbind(ID = 1:71, df)
df[df$ID==34, "Shopping_5"] <- "Somewhat disagree"
df <- df[df$Shopping_5 == "Somewhat disagree",]
df <- df %>% mutate_all(na_if,"")
df <- df[,-c(30)]
```

```{r}
# Dummy'ing the whole lot

# Q2
df$Q2[df$Q2 == "Female"]                     <- 0
df$Q2[df$Q2 == "Male"]                       <- 1
df$Q2[df$Q2 == "Non-binary / third gender"]  <- 0
df$Q2[df$Q2 == "Prefer not to say"]          <- 0


n <- c("Strongly Disagree"                   = 1, 
       "Disagree"                            = 2, 
       "Somewhat disagree"                   = 3, 
       "Neither agree nor disagree"          = 4, 
       "Somewhat agree"                      = 5, 
       "Agree"                               = 6, 
       "Strongly agree"                      = 7)

df$Cyberloafing_1D <- as.numeric(revalue(df$Cyberloafing_1, n))
df$Cyberloafing_2D <- as.numeric(revalue(df$Cyberloafing_2, n))
df$Cyberloafing_3D <- as.numeric(revalue(df$Cyberloafing_3, n))
df$Cyberloafing_4D <- as.numeric(revalue(df$Cyberloafing_4, n))
df$Cyberloafing_5D <- as.numeric(revalue(df$Cyberloafing_5, n))
df$Cyberloafing_6D <- as.numeric(revalue(df$Cyberloafing_6, n))
df$Cyberloafing_7D <- as.numeric(revalue(df$Cyberloafing_7, n))
df$Cyberloafing_8D <- as.numeric(revalue(df$Cyberloafing_8, n))
df$Cyberloafing_9D <- as.numeric(revalue(df$Cyberloafing_9, n))

df$Shopping_1D <- as.numeric(revalue(df$Shopping_1, n))
df$Shopping_2D <- as.numeric(revalue(df$Shopping_2, n))
df$Shopping_3D <- as.numeric(revalue(df$Shopping_3, n))
df$Shopping_4D <- as.numeric(revalue(df$Shopping_4, n))
df$Shopping_6D <- as.numeric(revalue(df$Shopping_6, n))
df$Shopping_7D <- as.numeric(revalue(df$Shopping_7, n))
df$Shopping_8D <- as.numeric(revalue(df$Shopping_8, n))

df$Access.Online.Conten_1D <- as.numeric(revalue(df$Access.Online.Conten_1, n))
df$Access.Online.Conten_2D <- as.numeric(revalue(df$Access.Online.Conten_2, n))
df$Access.Online.Conten_3D <- as.numeric(revalue(df$Access.Online.Conten_3, n))
df$Access.Online.Conten_4D <- as.numeric(revalue(df$Access.Online.Conten_4, n))
df$Access.Online.Conten_5D <- as.numeric(revalue(df$Access.Online.Conten_5, n))

m <- c("Never"         = 1,
       "Rarely"        = 2,
       "Sometimes"     = 3,
       "Often"         = 4,
       "Almost Always" = 5)

df$Productivity_1D <- as.numeric(revalue(df$Productivity_1, m))
df$Productivity_2D <- as.numeric(revalue(df$Productivity_2, m))
df$Productivity_3D <- as.numeric(revalue(df$Productivity_3, m))
df$Productivity_4D <- as.numeric(revalue(df$Productivity_4, m))
df$Productivity_5D <- as.numeric(revalue(df$Productivity_5, m))
df$Productivity_6D <- as.numeric(revalue(df$Productivity_6, m))
df$Productivity_7D <- as.numeric(revalue(df$Productivity_7, m))
df$Productivity_8D <- as.numeric(revalue(df$Productivity_8, m))
df$Productivity_9D <- as.numeric(revalue(df$Productivity_9, m))
df$Productivity_10D <- as.numeric(revalue(df$Productivity_10, m))
df$Productivity_11D <- as.numeric(revalue(df$Productivity_11, m))
df$Productivity_12D <- as.numeric(revalue(df$Productivity_12, m))
df$Productivity_13D <- as.numeric(revalue(df$Productivity_13, m))
df$Productivity_14D <- as.numeric(revalue(df$Productivity_14, m))
df$Productivity_15D <- as.numeric(revalue(df$Productivity_15, m))
df$Productivity_16D <- as.numeric(revalue(df$Productivity_16, m))
df$Productivity_17D <- as.numeric(revalue(df$Productivity_17, m))

o <- c("Trade School" = 1,
       "High School Graduate" = 2,
       "Bachelors Degree" = 3,
       "Masters Degree" = 4,
       "Ph.D. or higher" = 5,
       "Other" = 1)

df$Q4D <- as.numeric(revalue(df$Q4, o))
```

```{r}
#Establish row means of each cyberloafing variable
df$SharingM <- rowMeans(df[,55:63], na.rm = T)
df$ShoppingM <- rowMeans(df[,64:70], na.rm = T)
df$AccessM <- rowMeans(df[,71:75], na.rm = T)
df$ProductivityM <- rowMeans(df[,76:92], na.rm = T)

#Cyberloafing as a whole
df$CyberM <- rowMeans(df[,55:75], na.rm = T)
```

```{r}
#Regression
lm1 <- lm(ProductivityM ~ Q2 + Q4D, df)
summary(lm1)
lm2 <- lm(ProductivityM ~ CyberM, df)
summary(lm2)
df$Q4 <- relevel(factor(df$Q4), ref = "Ph.D. or higher")
lm3 <- lm(ProductivityM ~ Q2 * CyberM + Q3 * CyberM + Q4D * CyberM, df)
summary(lm3)

df$Q2 <- relevel(factor(df$Q2), ref = "2")
summary(lm(ProductivityM ~ Q8 + SharingM + ShoppingM + AccessM, data = df))

dff <- df[df$Q3 == "1960-1983" | df$Q3 == "1997+",]
dff2 <- df[df$Q3 == "1984-1996" | df$Q3 == "1997+",]
dff3 <- df[df$Q3 == "1984-1996" | df$Q3 == "1960-1983",]

t.test(dff$ProductivityM ~ dff$Q3)
t.test(dff2$ProductivityM ~ dff2$Q3)
t.test(dff3$ProductivityM ~ dff3$Q3)

t.test(dff$CyberM ~ dff$Q3)
t.test(dff2$CyberM ~ dff2$Q3)
t.test(dff3$CyberM ~ dff3$Q3)

mean(df$CyberM)
sd(df$CyberM)
mean(df$ProductivityM)
sd(df$ProductivityM)

df$Q3D_AGE[df$Q3 == "1960-1983"] <- 50
df$Q3D_AGE[df$Q3 == "1984-1996"] <- 31
df$Q3D_AGE[df$Q3 == "1997+"] <- 20

df$Q3D[df$Q3 == "1960-1983"] <- 0
df$Q3D[df$Q3 == "1984-1996"] <- 1
df$Q3D[df$Q3 == "1997+"] <- 2

cor(df$Q3D_AGE, df$ProductivityM)
cor(df$CyberM, df$ProductivityM)
cor(df$Q4D, df$CyberM)
cor(df$Q4D, df$ProductivityM)
cor(as.numeric(df$Q2), df$ProductivityM)
cor(as.numeric(df$Q2), df$CyberM)
cor(df$Q4D, as.numeric(df$Q2))
cor(df$Q3D, df$ProductivityM)
cor(df$Q3D, df$CyberM)
cor(df$Q4D, df$Q3D)
cor(df$Q3D, as.numeric(df$Q2))

############################
tapply(df$ProductivityM, df$Q3, mean)
tapply(df$ProductivityM, df$Q3, sd)

tapply(df$CyberM, df$Q3, mean)
tapply(df$CyberM, df$Q3, sd)

tapply(df$CyberM, df$Q3, mean)
tapply(df$CyberM, df$Q3, sd)
```

```{r}
cor <- round(cor(df[94:97], use = "pairwise.complete.obs"), 2)
cormat <- melt(cor)
ggplot(cormat, aes(x = Var1, y = Var2, fill = value)) + geom_tile() + geom_text(aes(Var1, Var2, label = value), color = "white")
```

```{r}
library(psych)
alpha(df[,55:63])
alpha(df[,64:70])
alpha(df[,71:75])
alpha(df[,76:92])
```





